### ISSUE TITLE
When navigation breadcrumbs are too long, text ellipsis is applied only to last item

### ISSUE THREAD

**Issue by michalsieron** [agersant/polaris-web#62]
Kinda related to #39. 

You can see here, that ellipsis is properly applied.
![PolarisOK](https://user-images.githubusercontent.com/54780569/90319711-d736a000-df3a-11ea-952e-88d9ad44ede3.png)

But here after navigating to CD1 it is no longer applied properly.
![PolarisNotOK](https://user-images.githubusercontent.com/54780569/90319930-ce46ce00-df3c-11ea-8a86-2fe31100df6f.png)

Polaris is running in docker container from [ogarcia/docker-polaris](https://github.com/ogarcia/docker-polaris).
Accessed on Firefox 79.0

I was thinking about possible solutions and came up with three:
  1. just calculate somehow for each item whether it should shrink (I don't know CSS, but I guess it should be possible)
  2. flow "pills" to next line (but apply ellipsis so there won't be lots of free space?)
  3. display it like fish shell in its default prompt (first letter of directory except current one)
  so in this example it would be (A) (M) (A) (F) (CD1)

**Comment by agersant** [comment]
Nice find!
Fixed in 09ce9a857d50418dd97b8f8338a780f7fd12c0dd:
![image](https://user-images.githubusercontent.com/817256/90324137-cdec0a00-df1f-11ea-9b6a-c936f63a7585.png)

Note that if you store albums spanning multiple discs in a single directory and tag the songs accordingly, you can get better looking UI like this (assuming you have cover art for the album too):

![image](https://user-images.githubusercontent.com/817256/90324188-6aaea780-df20-11ea-9c29-8f1554d68a26.png)
