### ISSUE TITLE
Bug: Multi-disc album gets queued alphabetically after clicking "Queue all"

### ISSUE THREAD

**Issue by michalsieron** [agersant/polaris-web#67]
If you have album containing multiple discs (but with all songs with proper tags in one directory) it will queue songs with alphabetic order instead of disc 1, then disc 2 and so on.

Polaris 0.12.4 on docker

**Comment by agersant** [comment]
I took a stab at fixing exactly the issue you described. However, I then discovered it was adding even more inconsistency than this bug describes, as the fix could only work from an album page (and not when queuing the same album from one if its parent directories).

As a result, I made a change which instead makes the behavior more consistent with what is on the screen. Songs in an album will now be listed (and queued) in filename alphabetical order, regardless of file metadata.

I do want to support this very legitimate use case, and I think the way to do it is to make it possible to browse the collection using song metadata instead of file system organization. This has come up a few times in the past so I finally set in motion the work to support this. I also created new tickets to keep track of it: 
- https://github.com/agersant/polaris/issues/92
- https://github.com/agersant/polaris-web/issues/68

Comments and suggestions on these would be very welcome.

In the meantime I am going to close this ticket as it is covered by these new additions.
