### ISSUE TITLE
add all button on albumview

### ISSUE THREAD

**Issue by jxs** [agersant/polaris-web#9]
is there already a way to add all of the songs on a current album?
if not, what do you think about that feature?
I was trying to add it to my fork, but i am having a problem because the viewmode on song listing can be `explorerView` or `albumView`, and it only makes sense adding that button for songs you use different views for song listing depending on the album having cover or not. What do you think about listing the songs only on albumView and add cover present logic?

update:
something like [this](https://github.com/jxs/polaris-web/commit/189362f675999d61a75b33af200cb0c807694465)

cheers :)

**Comment by agersant** [comment]
I tend to queue albums (or directories) by drag-and-dropping them from the parent level into the playlist, digging into albums only when I want to queue individual tracks. However, I can imagine the desire to see what's in the album (or directory) and queue everything after confirming it's the one you thought.

As you already found out, the only view that allows queuing everything is the albumView, in which the artwork can be drag-and-dropped. Rather than allowing image-less directories to use the album view, I think it would make more sense to add a "queue all" button on every view.

The implementation could also be a little simpler by re-using the flatten mechanism (which is used when dragging a directory into the playlist) to flatten the current directory.
